### ISSUE TITLE
Script file upload with commit msg or Version

### ISSUE THREAD

**Issue by Shelvak** [cirope/monitor#30]
Al crear un guión (y al modificarlo), no se guarda ningún registro de cambio. No sabes si cambio el nombre del archivo o si es el mismo con otro peso...

Habría que: 
- O versionar _algo_ del archivo.
- O pedir un commit msg siempre.

**Comment by francocatena** [comment]
No es mala, pero lo del archivo estoy 98% seguro que nadie lo usa. Creo que lo vamos a volar para soportar que suban un container.

Ahí si deberíamos pedir un mensaje, pero de última hacemos ese cambio cuando hagamos el otro.
